In [2]:
import numpy as np

In [3]:
nd1 = np.array([[1,2],[2,3],[3,4]])

In [4]:
print(nd1)

[[1 2]
 [2 3]
 [3 4]]


In [5]:
print(type(nd1))

<class 'numpy.ndarray'>


In [6]:
nd1.max()

4

In [7]:
nd1.min()

1

In [8]:
nd1[1]#取第一行

array([2, 3])

In [9]:
nd2 = np.array([["1","2"],["3","4"]])

In [10]:
print(nd2)

[['1' '2']
 ['3' '4']]


In [11]:
nd2.max()

TypeError: cannot perform reduce with flexible type

In [19]:
nd2 = nd2.astype("int")

In [20]:
nd2.max()

4

In [21]:
#索引
nd3 = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])

In [22]:
nd3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [24]:
nd3.shape #4行3列

(4, 3)

In [26]:
nd3[2]

array([7, 8, 9])

In [27]:
nd3[1:3:1]

array([[4, 5, 6],
       [7, 8, 9]])

In [28]:
#切片
#[行的切片,列的切片]
# [行的起始位置:行的结束位置:步长,列的起始位置:列的结束为止:步长]

In [30]:
nd3[1:3:1,1:3:1]

array([[5, 6],
       [8, 9]])

In [32]:
nd3[:,2] # 2表示取第二列，2：表示取第二列以及之后的都取上

array([3, 6, 9, 3])

In [43]:
nd4 = np.array(
[
    [0,1,2,3,4,5],
    [10,11,12,13,14,15],
    [20,21,22,23,24,25],
    [30,31,32,33,34,35],
    [40,41,42,43,44,45],
    [50,51,52,53,54,55]
])

nd4

In [38]:
#坐标
nd4[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [44]:
nd4[(0,2,5),2]

array([ 2, 22, 52])

In [45]:
nd5 = np.array([1,0,1,0,0,1],dtype='bool')

In [46]:
nd5

array([ True, False,  True, False, False,  True])

In [47]:
# 布尔索引
nd4[(nd5),2]

array([ 2, 22, 52])

In [48]:
nd4%2 == 1

array([[False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]])

In [49]:
nd4[nd4%2 == 1]

array([ 1,  3,  5, 11, 13, 15, 21, 23, 25, 31, 33, 35, 41, 43, 45, 51, 53,
       55])

In [50]:
nd1 = np.array([[1,2,3],[4,5,6]])

In [52]:
nd2 = np.array([[2,3,4],[1,2,3]])

In [54]:
nd1

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
nd2

array([[2, 3, 4],
       [1, 2, 3]])

In [58]:
# 对位运算
print(nd1 + nd2)
print(nd1 - nd2)
print(nd1 * nd2)
print(nd1 / nd2)

[[3 5 7]
 [5 7 9]]
[[-1 -1 -1]
 [ 3  3  3]]
[[ 2  6 12]
 [ 4 10 18]]
[[0.5        0.66666667 0.75      ]
 [4.         2.5        2.        ]]


In [61]:
# 矩阵运算
nd3 = np.array([[1,2],[2,3],[3,4]])

In [62]:
nd3

array([[1, 2],
       [2, 3],
       [3, 4]])

In [63]:
np.dot(nd1,nd3)

array([[14, 20],
       [32, 47]])

In [64]:
np.dot(nd1,1/nd3)

array([[3.        , 1.91666667],
       [8.5       , 5.16666667]])